In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\kdmod\anaconda3\lib\site-packages (4.17.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\kdmod\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\kdmod\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: trio~=0.17 in c:\users\kdmod\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\kdmod\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\kdmod\anaconda3\lib\site-packages (from selenium) (4.9.0)
Requirement already satisfied: outcome in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: exceptiongroup in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: idna in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: sortedcontainers in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\kdmod\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\kdmod\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\kdmod\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\kdmod\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\kdmod\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
from selenium.common.exceptions import StaleElementReferenceException

In [4]:
driver = webdriver.Chrome()
driver.get('https://www.rightmove.co.uk/for-sale/')
time.sleep(1)

In [5]:
area = input('Enter city name : ')

Enter city name : london

In [6]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [7]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [8]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [9]:
import re

In [10]:
purl =[]

In [12]:
start =0
end = 25
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [13]:
len(purl)

575

In [14]:
name_address=[]
p_type =[]
bedroom =[]
price=[]
bathroom=[]
carpetarea=[]
garden=[]
status=[]
parking =[]
ctax=[]

In [16]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [17]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(575, 575, 575, 575, 575)

In [18]:
driver.get('https://www.rightmove.co.uk/for-sale/') ## need to go from here

In [19]:
area = input('Enter UK city name : ')

Enter UK city name : bristol

In [20]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [21]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [22]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [23]:
purl= []
start =0
end = 30
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [24]:
len(purl)

750

In [25]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [26]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(1325, 1325, 1325, 1325, 1325)

In [27]:
driver.get('https://www.rightmove.co.uk/for-sale/') ### start from here 3rd

In [28]:
area = input('Enter City Name :')

Enter City Name :aylesbury

In [29]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [30]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [31]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [32]:
purl= []
start =0
end = 15
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [33]:
len(purl)

375

In [35]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [36]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(1700, 1700, 1700, 1700, 1700)

In [37]:
driver.get('https://www.rightmove.co.uk/for-sale/') ###4th

In [38]:
area = input('Enter City Name :')

Enter City Name :brentwood

In [39]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [40]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [41]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [42]:
purl= []
start =0
end = 10
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [43]:
len(purl)

250

In [44]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [45]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(1950, 1950, 1950, 1950, 1950)

In [46]:
driver.get('https://www.rightmove.co.uk/for-sale/') ###5th

In [47]:
area = input('Enter City Name :') #######

Enter City Name :hatfield

In [48]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [49]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [50]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [51]:
purl= []
start =0
end = 7
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [52]:
len(purl)

175

In [53]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [54]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(2125, 2125, 2125, 2125, 2125)

In [55]:
driver.get('https://www.rightmove.co.uk/for-sale/')

In [56]:
area = input('Enter City Name :')

Enter City Name :cambridge

In [57]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [58]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [59]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [60]:
purl= []
start =0
end = 7
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [61]:
len(purl)

175

In [62]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [63]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(2300, 2300, 2300, 2300, 2300)

In [64]:
driver.get('https://www.rightmove.co.uk/for-sale/')

In [65]:
area = input('Enter City Name :')

Enter City Name :manchester

In [66]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [67]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [68]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [69]:
purl= []
start =0
end = 9
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [70]:
len(purl)

225

In [71]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [72]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(2525, 2525, 2525, 2525, 2525)

In [73]:
driver.get('https://www.rightmove.co.uk/for-sale/')

In [74]:
area = input('Enter City Name :')

Enter City Name :leeds

In [75]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [76]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [77]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [78]:
purl= []
start =0
end = 9
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [79]:
len(purl)

225

In [80]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [81]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(2750, 2750, 2750, 2750, 2750)

In [82]:
driver.get('https://www.rightmove.co.uk/for-sale/')

In [83]:
area = input('Enter City Name :')

Enter City Name :reading

In [84]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [85]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [86]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [87]:
purl= []
start =0
end = 1
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [88]:
len(purl)

25

In [89]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [90]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(2775, 2775, 2775, 2775, 2775)

In [91]:
driver.get('https://www.rightmove.co.uk/for-sale/')

In [92]:
area = input('Enter City Name :')

Enter City Name :oxford

In [93]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [94]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [95]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [96]:
purl= []
start =0
end = 15
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [97]:
len(purl)

375

In [98]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [99]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(3150, 3150, 3150, 3150, 3150)

In [100]:
driver.get('https://www.rightmove.co.uk/for-sale/')

In [101]:
area = input('Enter City Name :')

Enter City Name :york

In [102]:
search = driver.find_element(By.XPATH,'//input[@class="searchBox ac_input"]')
search.send_keys(area)

In [103]:
s_button = driver.find_element(By.XPATH,'//input[@class="button "][1]')
s_button.click()

In [104]:
f_button = driver.find_element(By.XPATH,'//button[@class="button touchsearch-button touchsearch-primarybutton"]')
f_button.click()

In [105]:
purl= []
start =0
end = 4
for page in range(start,end):
    url = driver.find_elements(By.XPATH, '//a[@class="propertyCard-link property-card-updates"]')
    for i in url:
        purl.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'//button[@class="pagination-button pagination-direction pagination-direction--next"]')
    next_button.click()
    time.sleep(1)

In [106]:
len(purl)

100

In [107]:
for i in purl:
    driver.get(i)
    time.sleep(1)
    try:
        name = driver.find_element(By.XPATH,'//div[@class="h3U6cGyEUf76tvCpYisik"]/h1')
        name_address.append(name.text)
    except:
        name_address.append('-')
    try:
        pt = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[1]/dd/span/p')
        p_type.append(pt.text)
    except:
        p_type.append('-')    
    try:
        bed = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[2]/dd/span/p')
        bedroom.append(bed.text)
    except:
        bedroom.append('-')
    try:
        bath = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[3]/dd/span/p')
        bathroom.append(bath.text)
    except:
        bathroom.append('-')    
    try:
        price1 = driver.find_element(By.XPATH,'//div[@class="_1gfnqJ3Vtd1z40MlC0MzXu"]/span[1]')
        price.append(price1.text)
    except:
        price.append('-')    
    try:
        carea = driver.find_element(By.XPATH,'//dl[@class="_4hBezflLdgDMdFtURKTWh"]/div[4]/dd/span/p[1]')
        carpetarea.append(carea.text)
    except:
        carpetarea.append('-')
    try:
        gard = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[3]/dd/span')
        garden.append(gard.text)
    except:
        garden.append('-')
    try:
        stat = driver.find_element(By.XPATH,'//div[@class="_32IXcntQDSML3xVUkSdyXN"]')
        status.append(stat.text)
    except:
        status.append('-')
    try:
        park = driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[2]/dd/span')
        parking.append(park.text)
    except:
        parking.append('-')
    try:
        tax= driver.find_element(By.XPATH,'//dl[@class="_1H0UoH91Rh0KKGH7JRGxEd"]/div[1]/dd')
        ctax.append(tax.text)
    except:
        ctax.append('-')

In [108]:
len(price), len(p_type), len(bedroom),len(name_address),len(bathroom),
len(carpetarea), len(garden), len(status),len(parking), len(ctax)

(3250, 3250, 3250, 3250, 3250)

In [109]:
df = pd.DataFrame(list(zip(name_address,price,bedroom,p_type,bathroom,carpetarea,garden,status,parking,ctax )),
                  columns=['Property_Name', 'Price','No_of_Bedroom','Property_type','No_of_Bathroom', 'Carpet_Area', 'Garden', 'Property Status','Parking','Council_Tax'])
df

,Property_Name,Price,No_of_Bedroom,Property_type,No_of_Bathroom,Carpet_Area,Garden,Property Status,Parking,Council_Tax
0,"Beaumont Avenue, Fulham","£925,000",3,Flat,2,Ask agent,Ask agent,TENURE\nShare of Freehold,Ask agent,Ask agent
1,"One Hyde Park, Knightsbridge","£60,000,000",5,Apartment,5,Ask agent,Terrace,TENURE\nLeasehold,Garage,Ask agent
2,"Buckingham Gate, Westminster, SW1E","£45,000,000",8,Terraced,9,Ask agent,Communal garden,-,Garage,Ask agent
3,"Buckingham Gate, SW1","£45,000,000",9,Terraced,9,"15,845 sq ft",Ask agent,-,Yes,Band: H
4,"Belgravia Gate, Grosvenor Crescent, Belgravia,...","£43,700,000",7,6,Ask agent,-,Ask agent,TENURE\nLeasehold,Yes,Ask agent
...,...,...,...,...,...,...,...,...,...,...
3245,"St. Saviours Place, York, YO1 7PJ","£650,000",3,Apartment,3,"1,255 sq ft",Ask agent,TENURE\nLeasehold,Yes,Band: G
3246,"Mount Terrace, York, North Yorkshire, YO24","£650,000",3,Terraced,2,"1,351 sq ft",Yes,-,Ask agent,Band: E
3247,"47 Holgate Road, York","£650,000",4,House,2,"2,125 sq ft",Yes,-,Yes,Band: C
3248,"Grosvenor Road, Off Bootham, York","£650,000",3,Semi-Detached,2,Ask agent,Yes,-,Yes,Band: TBC
3249,"Carousel House Joseph Terry Grove, North Yorks...","£650,000",2,Penthouse,2,Ask agent,Ask agent,-,Yes,Band: TBC

In [110]:
df[df.columns[1:3]] = df[df.columns[1:3]].replace('[\£,]', '', regex=True)
df

,Property_Name,Price,No_of_Bedroom,Property_type,No_of_Bathroom,Carpet_Area,Garden,Property Status,Parking,Council_Tax
0,"Beaumont Avenue, Fulham",925000,3,Flat,2,Ask agent,Ask agent,TENURE\nShare of Freehold,Ask agent,Ask agent
1,"One Hyde Park, Knightsbridge",60000000,5,Apartment,5,Ask agent,Terrace,TENURE\nLeasehold,Garage,Ask agent
2,"Buckingham Gate, Westminster, SW1E",45000000,8,Terraced,9,Ask agent,Communal garden,-,Garage,Ask agent
3,"Buckingham Gate, SW1",45000000,9,Terraced,9,"15,845 sq ft",Ask agent,-,Yes,Band: H
4,"Belgravia Gate, Grosvenor Crescent, Belgravia,...",43700000,7,6,Ask agent,-,Ask agent,TENURE\nLeasehold,Yes,Ask agent
...,...,...,...,...,...,...,...,...,...,...
3245,"St. Saviours Place, York, YO1 7PJ",650000,3,Apartment,3,"1,255 sq ft",Ask agent,TENURE\nLeasehold,Yes,Band: G
3246,"Mount Terrace, York, North Yorkshire, YO24",650000,3,Terraced,2,"1,351 sq ft",Yes,-,Ask agent,Band: E
3247,"47 Holgate Road, York",650000,4,House,2,"2,125 sq ft",Yes,-,Yes,Band: C
3248,"Grosvenor Road, Off Bootham, York",650000,3,Semi-Detached,2,Ask agent,Yes,-,Yes,Band: TBC
3249,"Carousel House Joseph Terry Grove, North Yorks...",650000,2,Penthouse,2,Ask agent,Ask agent,-,Yes,Band: TBC

In [111]:
df[df.columns[1:3]] = df[df.columns[1:3]].replace('[^.0-9]', '', regex=True)
df

,Property_Name,Price,No_of_Bedroom,Property_type,No_of_Bathroom,Carpet_Area,Garden,Property Status,Parking,Council_Tax
0,"Beaumont Avenue, Fulham",925000,3,Flat,2,Ask agent,Ask agent,TENURE\nShare of Freehold,Ask agent,Ask agent
1,"One Hyde Park, Knightsbridge",60000000,5,Apartment,5,Ask agent,Terrace,TENURE\nLeasehold,Garage,Ask agent
2,"Buckingham Gate, Westminster, SW1E",45000000,8,Terraced,9,Ask agent,Communal garden,-,Garage,Ask agent
3,"Buckingham Gate, SW1",45000000,9,Terraced,9,"15,845 sq ft",Ask agent,-,Yes,Band: H
4,"Belgravia Gate, Grosvenor Crescent, Belgravia,...",43700000,7,6,Ask agent,-,Ask agent,TENURE\nLeasehold,Yes,Ask agent
...,...,...,...,...,...,...,...,...,...,...
3245,"St. Saviours Place, York, YO1 7PJ",650000,3,Apartment,3,"1,255 sq ft",Ask agent,TENURE\nLeasehold,Yes,Band: G
3246,"Mount Terrace, York, North Yorkshire, YO24",650000,3,Terraced,2,"1,351 sq ft",Yes,-,Ask agent,Band: E
3247,"47 Holgate Road, York",650000,4,House,2,"2,125 sq ft",Yes,-,Yes,Band: C
3248,"Grosvenor Road, Off Bootham, York",650000,3,Semi-Detached,2,Ask agent,Yes,-,Yes,Band: TBC
3249,"Carousel House Joseph Terry Grove, North Yorks...",650000,2,Penthouse,2,Ask agent,Ask agent,-,Yes,Band: TBC

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3250 entries, 0 to 3249
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Property_Name    3250 non-null   object
 1   Price            3250 non-null   object
 2   No_of_Bedroom    3250 non-null   object
 3   Property_type    3250 non-null   object
 4   No_of_Bathroom   3250 non-null   object
 5   Carpet_Area      3250 non-null   object
 6   Garden           3250 non-null   object
 7   Property Status  3250 non-null   object
 8   Parking          3250 non-null   object
 9   Council_Tax      3250 non-null   object
dtypes: object(10)
memory usage: 254.0+ KB

In [113]:
df['Price'] = df['Price'].str.replace('\W', '', regex=True)

In [115]:
df['No_of_Bedroom'] = df['No_of_Bedroom'].str.replace('\W', '', regex=True)

In [116]:
df['No_of_Bathroom'] = df['No_of_Bathroom'].str.replace('\W', '', regex=True)

In [117]:
df.isnull().sum()

Property_Name      0
Price              0
No_of_Bedroom      0
Property_type      0
No_of_Bathroom     0
Carpet_Area        0
Garden             0
Property Status    0
Parking            0
Council_Tax        0
dtype: int64

In [118]:
df.dropna(inplace = True)

In [119]:
df['Price'] = df['Price'].str.extract('(\d+)').astype(float)

In [120]:
df['No_of_Bedroom'] = df['No_of_Bedroom'].str.extract('(\d+)').astype(float)

In [121]:
df['No_of_Bathroom'] = df['No_of_Bathroom'].str.extract('(\d+)').astype(float)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3250 entries, 0 to 3249
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Property_Name    3250 non-null   object
 1   Price            3246 non-null   float64
 2   No_of_Bedroom    3222 non-null   float64
 3   Property_type    3250 non-null   object
 4   No_of_Bathroom   3073 non-null   float64
 5   Carpet_Area      3250 non-null   object
 6   Garden           3250 non-null   object
 7   Property Status  3250 non-null   object
 8   Parking          3250 non-null   object
 9   Council_Tax      3250 non-null   object
dtypes: float64(3), object(7)
memory usage: 254.0+ KB

In [123]:
df.isnull().sum()

Property_Name        0
Price                4
No_of_Bedroom       28
Property_type        0
No_of_Bathroom     177
Carpet_Area          0
Garden               0
Property Status      0
Parking              0
Council_Tax          0
dtype: int64

In [124]:
df.dropna(inplace = True)

In [125]:
df.isnull().sum()

Property_Name      0
Price              0
No_of_Bedroom      0
Property_type      0
No_of_Bathroom     0
Carpet_Area        0
Garden             0
Property Status    0
Parking            0
Council_Tax        0
dtype: int64

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3073 entries, 0 to 3249
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Property_Name    3073 non-null   object
 1   Price            3073 non-null   float64
 2   No_of_Bedroom    3073 non-null   float64
 3   Property_type    3073 non-null   object
 4   No_of_Bathroom   3073 non-null   float64
 5   Carpet_Area      3073 non-null   object
 6   Garden           3073 non-null   object
 7   Property Status  3073 non-null   object
 8   Parking          3073 non-null   object
 9   Council_Tax      3073 non-null   object
dtypes: float64(3), object(7)
memory usage: 264.1+ KB

In [127]:
df.sample(50)

,Property_Name,Price,No_of_Bedroom,Property_type,No_of_Bathroom,Carpet_Area,Garden,Property Status,Parking,Council_Tax
2457,King street,330000.0,2.0,Apartment,1.0,Ask agent,Yes,TENURE\nLeasehold,Ask agent,Band: TBC
1345,"King Edward Avenue, Aylesbury",695000.0,4.0,Detached,1.0,"1,733 sq ft",Yes,-,Yes,Band: F
1151,"Royal Victoria Park, BS10 6TD, Bristol",550000.0,3.0,Terraced,2.0,Ask agent,Yes,-,Yes,Ask agent
1785,"Spurgate, Hutton, Brentwood",1350000.0,4.0,Detached,4.0,Ask agent,Yes,-,Ask agent,Ask agent
1759,"Hutton Gate, Hutton Mount, Brentwood",1600000.0,4.0,Detached,2.0,Ask agent,Yes,-,Yes,Ask agent
522,"Grosvenor Square, Mayfair",9250000.0,2.0,Flat,3.0,"2,465 sq ft",Yes,TENURE\nLeasehold,Yes,Ask agent
1500,"New Street, Aylesbury",176000.0,1.0,Apartment,1.0,Ask agent,Yes,TENURE\nLeasehold,Yes,Band: TBC
3041,"Hill View Road, Oxford",725000.0,3.0,Terraced,2.0,Ask agent,Private garden,-,On street,Band: E
1878,"Shenfield Road, Shenfield, Brentwood",925000.0,2.0,Apartment,2.0,"1,385 sq ft",Ask agent,TENURE\nLeasehold,Yes,Band: F
1718,"Hay Green Lane, Hook End, CM15",2700000.0,6.0,Detached,4.0,Ask agent,Yes,-,Yes,Band: H
923,"Wellington Terrace, Clifton, Bristol BS8",675000.0,2.0,Terraced,1.0,"1,190 sq ft",Ask agent,-,Ask agent,Band: D
1065,"Longmead Avenue, Bishopston, Bristol",590000.0,5.0,Terraced,2.0,Ask agent,Yes,-,Ask agent,Band: C
822,"Nutgrove Avenue, Victoria Park",750000.0,4.0,Terraced,2.0,Ask agent,Yes,-,Ask agent,Band: D
2931,"Cumnor Hill, Oxford, OX2",995000.0,4.0,Detached,3.0,Ask agent,Yes,-,Yes,Ask agent
2011,"Plot 13, The Carmack, Havilland Park, Hatfield",505000.0,4.0,Terraced,2.0,"1,143 sq ft",Yes,-,Yes,Ask agent
2662,"Woodlands Drive, Rawdon, Leeds, West Yorkshire...",950000.0,5.0,House,4.0,Ask agent,Yes,-,Yes,Band: G
1580,"Mandeville Road, AYLESBURY",375000.0,3.0,Semi-Detached,1.0,Ask agent,"Back garden,",-,Off street,Band: C
1296,"Northover Road, Westbury, Bristol, BS9",490000.0,4.0,Town House,2.0,Ask agent,Yes,-,Yes,Band: D
2693,"Rose Croft, East Keswick, LS17",875000.0,5.0,Detached,2.0,Ask agent,Yes,-,Yes,Band: G
1477,"Prince Rupert Drive, Aylesbury, HP19",450000.0,5.0,Terraced,2.0,Ask agent,Private garden,-,Garage,Band: D
934,"Beaconlea, Bristol",665000.0,4.0,Detached,2.0,Ask agent,Yes,-,Yes,Band: D
1665,"St. Annes Road, AYLESBURY, HP19 7RB",315000.0,3.0,Terraced,1.0,Ask agent,Yes,-,Yes,Band: B
481,"Damac Towers, Nine Elms",9601000.0,5.0,Penthouse,5.0,Ask agent,Terrace,TENURE\nLeasehold,Off street,Ask agent
850,"Manor Gardens, Bristol",610000.0,4.0,Semi-Detached,3.0,Ask agent,Yes,-,Ask agent,Band: TBC
959,"Falcondale Road, Westbury On Trym",650000.0,3.0,Semi-Detached,1.0,Ask agent,Yes,-,Yes,Ask agent
1240,"Frenchay Hill, Frenchay.",500000.0,4.0,Semi-Detached,1.0,"1,442 sq ft",Yes,-,Ask agent,Ask agent
2950,"Marston, Oxford, OX3",750000.0,3.0,Semi-Detached,1.0,699 sq ft,Yes,-,"Garage,",Band: D
431,"Daleham Gardens, Hampstead, NW3",9950000.0,7.0,House,6.0,Ask agent,Yes,-,Yes,Ask agent
1295,"Queensholm Drive, Bristol, South Gloucestershi...",490000.0,3.0,Semi-Detached,1.0,Ask agent,Yes,-,Yes,Band: TBC
1012,"Jacob Street, Bristol, BS2",615000.0,4.0,Terraced,3.0,Ask agent,Yes,-,Yes,Band: TBC
569,"Warwick Gardens, London, W14",8950000.0,6.0,Semi-Detached,4.0,"5,208 sq ft",Yes,-,Yes,Band: H
1764,"Blackmore Road, Brentwood, CM15",1500000.0,4.0,Detached,3.0,Ask agent,Yes,-,Yes,Band: G
2378,"Viadux, Deansgate, Manchester, M1",430000.0,2.0,Apartment,2.0,Ask agent,Ask agent,-,Ask agent,Ask agent
2834,"London Road, Headington, Oxford",1650000.0,6.0,Detached,5.0,Ask agent,Yes,-,Yes,Band: TBC
1921,"Friars Avenue, Shenfield, Essex, CM15",835000.0,4.0,Semi-Detached,2.0,Ask agent,Yes,-,Yes,Ask agent
1854,"Roman Road, Shenfield",1000000.0,4.0,Detached,3.0,Ask agent,Yes,-,Yes,Ask agent
1356,"Malvern Road, Aylesbury, Buckinghamshire",650000.0,4.0,Detached,1.0,Ask agent,Yes,-,Yes,Band: E
2377,"New Elm Road, Manchester, Greater Manchester, M3",434990.0,2.0,Apartment,2.0,876 sq ft,Ask agent,TENURE\nLeasehold,Ask agent,Ask agent
3238,"The Pastures, Dringhouses, York YO24 2JE",675000.0,4.0,Detached,2.0,Ask agent,Yes,-,Yes,Band: E
1101,"Redwood Drive, Bristol, BS8",575000.0,2.0,Apartment,2.0,930 sq ft,Terrace,TENURE\nLeasehold,Allocated,Ask agent
915,Richmond Road | Montpelier,675000.0,4.0,Terraced,2.0,Ask agent,Yes,-,Ask agent,Band: C
2715,"Avon Close, Shadwell, LS17",850000.0,5.0,Detached,2.0,Ask agent,Yes,-,Yes,Band: G
2928,"Marston Ferry Road, Oxford, Oxfordshire, OX2",1000000.0,3.0,Flat,2.0,"1,506 sq ft",Yes,TENURE\nShare of Freehold,Yes,Band: C
2271,"Eden Street, Cambridge, Cambridgeshire, CB1",700000.0,3.0,Terraced,1.0,923 sq ft,Yes,-,Yes,Band: E
1996,"Gorseway, Hatfield, Hertfordshire, AL10",550000.0,3.0,End of Terrace,1.0,786 sq ft,Yes,-,Yes,Band: D
2456,"Slate Street, Manchester",330000.0,1.0,Apartment,1.0,550 sq ft,Ask agent,TENURE\nLeasehold,Ask agent,Band: TBC
2496,"Wharfside Apartments, Manchester, Greater Manc...",299990.0,1.0,Apartment,1.0,450 sq ft,Ask agent,-,Yes,Ask agent
1699,"Hastoe Park, Aylesbury",300000.0,2.0,Semi-Detached,1.0,871 sq ft,Ask agent,-,Yes,Band: B
2827,"Church Way, Iffley, Oxford, Oxfordshire, OX4",1750000.0,4.0,Detached,2.0,"2,584-3,468 sq ft",Yes,-,Yes,Band: G
919,"North Road, St. Andrews, Bristol, BS6",675000.0,3.0,Terraced,3.0,Ask agent,Yes,-,Ask agent,Band: TBC

##### Now as all prices are in GBP we need to convert all to INR values

###### Current GBP to INR rate is £1 = Rs 106.01

In [128]:
import math
from math import floor, ceil

In [129]:
df['Price'] = round(df['Price']* 106.01,2).astype(int)
df

,Property_Name,Price,No_of_Bedroom,Property_type,No_of_Bathroom,Carpet_Area,Garden,Property Status,Parking,Council_Tax
0,"Beaumont Avenue, Fulham",98059250,3.0,Flat,2.0,Ask agent,Ask agent,TENURE\nShare of Freehold,Ask agent,Ask agent
1,"One Hyde Park, Knightsbridge",-2147483648,5.0,Apartment,5.0,Ask agent,Terrace,TENURE\nLeasehold,Garage,Ask agent
2,"Buckingham Gate, Westminster, SW1E",-2147483648,8.0,Terraced,9.0,Ask agent,Communal garden,-,Garage,Ask agent
3,"Buckingham Gate, SW1",-2147483648,9.0,Terraced,9.0,"15,845 sq ft",Ask agent,-,Yes,Band: H
5,"Wilton Crescent, London, SW1X",-2147483648,8.0,Terraced,8.0,"9,049 sq ft",Ask agent,-,Yes,Band: H
...,...,...,...,...,...,...,...,...,...,...
3245,"St. Saviours Place, York, YO1 7PJ",68906500,3.0,Apartment,3.0,"1,255 sq ft",Ask agent,TENURE\nLeasehold,Yes,Band: G
3246,"Mount Terrace, York, North Yorkshire, YO24",68906500,3.0,Terraced,2.0,"1,351 sq ft",Yes,-,Ask agent,Band: E
3247,"47 Holgate Road, York",68906500,4.0,House,2.0,"2,125 sq ft",Yes,-,Yes,Band: C
3248,"Grosvenor Road, Off Bootham, York",68906500,3.0,Semi-Detached,2.0,Ask agent,Yes,-,Yes,Band: TBC
3249,"Carousel House Joseph Terry Grove, North Yorks...",68906500,2.0,Penthouse,2.0,Ask agent,Ask agent,-,Yes,Band: TBC

In [130]:
df['Price'] = df['Price'].apply(abs)
df.head(25)

,Property_Name,Price,No_of_Bedroom,Property_type,No_of_Bathroom,Carpet_Area,Garden,Property Status,Parking,Council_Tax
0,"Beaumont Avenue, Fulham",98059250,3.0,Flat,2.0,Ask agent,Ask agent,TENURE\nShare of Freehold,Ask agent,Ask agent
1,"One Hyde Park, Knightsbridge",2147483648,5.0,Apartment,5.0,Ask agent,Terrace,TENURE\nLeasehold,Garage,Ask agent
2,"Buckingham Gate, Westminster, SW1E",2147483648,8.0,Terraced,9.0,Ask agent,Communal garden,-,Garage,Ask agent
3,"Buckingham Gate, SW1",2147483648,9.0,Terraced,9.0,"15,845 sq ft",Ask agent,-,Yes,Band: H
5,"Wilton Crescent, London, SW1X",2147483648,8.0,Terraced,8.0,"9,049 sq ft",Ask agent,-,Yes,Band: H
6,"Addison Road, London, W14",2147483648,8.0,Detached,6.0,"9,544 sq ft",Yes,-,Yes,Band: H
7,"Brick Street, Mayfair, London, W1J",2147483648,7.0,House,7.0,Ask agent,Yes,-,Yes,Band: H
8,"Chester Square, London, SW1W",2147483648,6.0,Terraced,5.0,Ask agent,Yes,-,Yes,Band: H
9,"Addison Road, Holland Park, W14",2147483648,8.0,Detached,6.0,Ask agent,Yes,-,Yes,Band: H
10,"Royal Westminster, London",2147483648,7.0,Detached,5.0,"11,065 sq ft",Ask agent,-,Ask agent,Ask agent
11,"Brick Street, Mayfair, London, W1J",2147483648,7.0,Terraced,5.0,"12,831 sq ft",Ask agent,-,Yes,Band: H
12,"Chester Square, London, SW1W",2147483648,6.0,Terraced,5.0,"8,761 sq ft",Yes,-,Yes,Band: H
13,"Merton Lane, London, N6",2147483648,6.0,Detached,7.0,"18,239 sq ft",Yes,-,Yes,Band: TBC
14,"Merton Lane, London, N6",2147483648,6.0,Detached,7.0,Ask agent,Yes,-,Yes,Band: TBC
15,"Merton Lane, London, N6",2147483648,10.0,Detached,9.0,"18,238 sq ft",Yes,-,Yes,Band: H
16,"Merton Lane, Highgate, London, N6",2147483648,5.0,House,13807.0,Freehold,Yes,-,Ask agent,Band: TBC
17,"FREEHOLD House in Park Street, Mayfair, W1K",2147483648,11.0,Terraced,11.0,Ask agent,Ask agent,-,Ask agent,Band: H
18,"Avenue Road, NW8",2147483648,8.0,Detached,3.0,"5,585 sq ft",Yes,-,Yes,Band: H
19,"Princes Gate, Knightsbridge, London, SW7",2147483648,12.0,Detached,10.0,Ask agent,Ask agent,-,Ask agent,Band: H
20,"Cadogan Place, Belgravia, London, SW1X",2147483648,6.0,Terraced,7.0,"7,798 sq ft",Ask agent,-,Ask agent,Band: I
21,"Cambridge Park, Twickenham, Richmond, TW1.",2147483648,9.0,Detached,10.0,"18,834 sq ft",Yes,-,Yes,Band: H
22,"Cambridge Park, Twickenham, Greater London, TW1",2147483648,9.0,Detached,12.0,"18,837 sq ft",Yes,-,Yes,Ask agent
23,"Piccadilly, Mayfair",2147483648,6.0,House,6.0,"15,608 sq ft",Ask agent,-,Yes,Ask agent
24,"Princes Gate, London, SW7",2147483648,7.0,Terraced,6.0,"9,430 sq ft",Terrace,-,Ask agent,Ask agent
25,"Blundell Street, Caledonian Road, London, N7",58305500,3.0,Maisonette,1.0,979 sq ft,Yes,TENURE\nLeasehold,Yes,Band: D

In [131]:
df.to_csv('UK_Property_info.csv', na_rep='NULL')